import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { HashLoader } from "react-spinners";
import type { InferGetStaticPropsType, GetStaticProps } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import { analyzeUser, analyzeUserCommunityView } from "@/lib/utils/openai";
import { tweetsToTokenText } from "@/lib/utils";
import {
  getRecentTweetsToUser,
  getTweetsFromUser,
  getTwitterId,
} from "@/lib/utils/twitter";

export default function User({
  name,
  username,
  pic,
  result,
  toAnalysis,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const router = useRouter();
  const { status } = useSession();

  if (status === "loading") {
    return (
      <main className="flex flex-col items-center justify-center min-h-screen">
        <p>Loading...</p>
      </main>
    );
  }

  if (status === "unauthenticated") {
    return (
      <main className="flex flex-col items-center justify-center min-h-screen">
        <p>
          <button type="button" onClick={() => signIn()}>
            Sign in
          </button>
        </p>
      </main>
    );
  }

  return (
    <>
      <Head>
        <title>{`Perspec - ${router.isFallback ? "loading" : username}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center min-h-screen">
        <div className="w-full flex justify-end px-8 py-4">
          <button type="button" onClick={() => signOut()}>
            Sign out
          </button>
        </div>
        <div className="flex flex-col px-8 max-w-6xl flex-grow items-center justify-center">
          {!router.isFallback ? (
            <>
              {pic && (
                <Image
                  src={pic}
                  width={150}
                  height={150}
                  priority
                  quality={100}
                  className="rounded-full"
                  alt=""
                />
              )}
              <p className="mt-1 font-bold text-4xl">{`@${username.replace(
                "@",
                ""
              )}`}</p>
              <p className="text-md mt-1">{name}</p>
              <p className="w-full font-bold mt-8">{`Analysis of @${username}'s tweets`}</p>
              <p className="whitespace-pre-wrap">{result.trim()}</p>
              <p className="w-full font-bold mt-8">{`What people are saying about @${username}`}</p>
              <p className="whitespace-pre-wrap">{toAnalysis.trim()}</p>
            </>
          ) : (
            <div className="flex items-center h-full justify-center">
              <HashLoader size={100} />
            </div>
          )}
        </div>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const username = context.params?.username as string | undefined;

  if (!username) {
    return {
      notFound: true,
    };
  }

  const { name, id, pic } = await getTwitterId(username);

  if (!id || !name) {
    return {
      props: {
        name: "Unknown Person",
        username,
        pic: null,
        result:
          "Failed to find matching twitter user. Please check username and try again.",
        toAnalysis: "",
      },
      revalidate: false,
    };
  }
  const tweetsTo = await getRecentTweetsToUser(id, username);
  const tweetsFrom = await getTweetsFromUser(2, id, true, true);
  if (tweetsFrom.length === 0 || tweetsTo.length === 0) {
    return {
      props: {
        name,
        username,
        pic,
        result: "Couldn't retreieve any tweets from this user.",
        toAnalysis: "Failed to retreive tweets about this user.",
      },
      revalidate: 180,
    };
  }

  const toTweetText = await tweetsToTokenText(tweetsTo, 2500);
  const tweetText = await tweetsToTokenText(tweetsFrom, 3000);
  const [toAnalysis, analysis] = await Promise.all([
    analyzeUserCommunityView(name, username, toTweetText),
    analyzeUser(name, username, tweetText),
  ]);

  if (analysis.length === 0 || toAnalysis.length === 0) {
    return {
      props: {
        name,
        username,
        pic,
        result:
          "Failed to get analysis. Likely Open AI API is overloaded or too many requests. Please try again after a few minutes.",
        toAnalysis:
          "Failed to get analysis. Likely Open AI API is overloaded or too many requests. Please try again after a few minutes.",
      },
      revalidate: 180,
    };
  }

  return {
    props: { name, username, pic, result: analysis, toAnalysis },
    revalidate: false,
  };
};

export async function getStaticPaths() {
  return {
    paths: [{ params: { username: "elonmusk" } }],
    fallback: true,
  };
}
